In [70]:
import numpy as np
import matplotlib.pyplot as plt

In [71]:
src = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
dataset = np.genfromtxt(src, delimiter=",", dtype = str)

#  optimal value of k is sqrt(N)
k = int(np.sqrt(len(dataset))) + 1

print(dataset)

[['5.1' '3.5' '1.4' '0.2' 'Iris-setosa']
 ['4.9' '3.0' '1.4' '0.2' 'Iris-setosa']
 ['4.7' '3.2' '1.3' '0.2' 'Iris-setosa']
 ['4.6' '3.1' '1.5' '0.2' 'Iris-setosa']
 ['5.0' '3.6' '1.4' '0.2' 'Iris-setosa']
 ['5.4' '3.9' '1.7' '0.4' 'Iris-setosa']
 ['4.6' '3.4' '1.4' '0.3' 'Iris-setosa']
 ['5.0' '3.4' '1.5' '0.2' 'Iris-setosa']
 ['4.4' '2.9' '1.4' '0.2' 'Iris-setosa']
 ['4.9' '3.1' '1.5' '0.1' 'Iris-setosa']
 ['5.4' '3.7' '1.5' '0.2' 'Iris-setosa']
 ['4.8' '3.4' '1.6' '0.2' 'Iris-setosa']
 ['4.8' '3.0' '1.4' '0.1' 'Iris-setosa']
 ['4.3' '3.0' '1.1' '0.1' 'Iris-setosa']
 ['5.8' '4.0' '1.2' '0.2' 'Iris-setosa']
 ['5.7' '4.4' '1.5' '0.4' 'Iris-setosa']
 ['5.4' '3.9' '1.3' '0.4' 'Iris-setosa']
 ['5.1' '3.5' '1.4' '0.3' 'Iris-setosa']
 ['5.7' '3.8' '1.7' '0.3' 'Iris-setosa']
 ['5.1' '3.8' '1.5' '0.3' 'Iris-setosa']
 ['5.4' '3.4' '1.7' '0.2' 'Iris-setosa']
 ['5.1' '3.7' '1.5' '0.4' 'Iris-setosa']
 ['4.6' '3.6' '1.0' '0.2' 'Iris-setosa']
 ['5.1' '3.3' '1.7' '0.5' 'Iris-setosa']
 ['4.8' '3.4' '1

In [72]:
#removed 'label' row to get features dataset
features = np.delete(dataset,-1,1) 

features = np.zeros([len(dataset),len(dataset[0])-1],dtype="float")

for i in range(len(features)):
    for j in range(len(features[0])):
        features[i][j] = float(dataset[i][j])


print(features[:20])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]]


In [73]:
#encoding labels to numeric values
for i in range(150):
    if dataset[i][4] == "Iris-setosa":
        dataset[i][4] = 0
    elif dataset[i][4] == 'Iris-versicolor':
        dataset[i][4] = 1
    elif dataset [i][4] == 'Iris-virginica':
        dataset[i][4] = 2

x_train, x_test = dataset[:110,:], dataset[110:,:]
print(x_train[:20])



[['5.1' '3.5' '1.4' '0.2' '0']
 ['4.9' '3.0' '1.4' '0.2' '0']
 ['4.7' '3.2' '1.3' '0.2' '0']
 ['4.6' '3.1' '1.5' '0.2' '0']
 ['5.0' '3.6' '1.4' '0.2' '0']
 ['5.4' '3.9' '1.7' '0.4' '0']
 ['4.6' '3.4' '1.4' '0.3' '0']
 ['5.0' '3.4' '1.5' '0.2' '0']
 ['4.4' '2.9' '1.4' '0.2' '0']
 ['4.9' '3.1' '1.5' '0.1' '0']
 ['5.4' '3.7' '1.5' '0.2' '0']
 ['4.8' '3.4' '1.6' '0.2' '0']
 ['4.8' '3.0' '1.4' '0.1' '0']
 ['4.3' '3.0' '1.1' '0.1' '0']
 ['5.8' '4.0' '1.2' '0.2' '0']
 ['5.7' '4.4' '1.5' '0.4' '0']
 ['5.4' '3.9' '1.3' '0.4' '0']
 ['5.1' '3.5' '1.4' '0.3' '0']
 ['5.7' '3.8' '1.7' '0.3' '0']
 ['5.1' '3.8' '1.5' '0.3' '0']]


In [74]:
def dist(p1,p2):
    
    dist2 = 0
    
    for i in range(4):
        dist2 += (float(p1[i])-float(p2[i]))**2

    return(np.sqrt(dist2))

In [75]:
#creating arrays of distance vectors
distArr = np.zeros([110,2])
for i in range(110):    
    distArr[i][1] = i

#x_test[5] as ex
for i in range(110):    
    distArr[i][0] = dist(x_train[i],x_test[5])

print(distArr[:20])

[[ 4.6260134   0.        ]
 [ 4.6808119   1.        ]
 [ 4.82700735  2.        ]
 [ 4.70106371  3.        ]
 [ 4.66261729  4.        ]
 [ 4.24970587  5.        ]
 [ 4.74236228  6.        ]
 [ 4.56618002  7.        ]
 [ 4.86929153  8.        ]
 [ 4.64112055  9.        ]
 [ 4.48330235 10.        ]
 [ 4.54972527 11.        ]
 [ 4.75920161 12.        ]
 [ 5.1894123  13.        ]
 [ 4.7138095  14.        ]
 [ 4.46989933 15.        ]
 [ 4.59347363 16.        ]
 [ 4.58148448 17.        ]
 [ 4.22018957 18.        ]
 [ 4.52658812 19.        ]]


In [76]:
sortarr = distArr[:,0].argsort()
print(sortarr)

Nearest_Neighbours = np.zeros([k,1],)
  
for i in range(k):
    
    Nearest_Neighbours[i] = dataset[sortarr[i]][4]

print(Nearest_Neighbours)


[104 103 100  77  70 101  56 102  83  52 108  86  51  72  54  85  63  76
  91 109  50  78  58  75  65  73  66  74  97  61 107  55  84  68  87  96
  71  95  99  94  88  90 105  92 106  67  82  89  53  59  69  62  64  80
  81  79  60  93  57  98  44  18  23   5  20  24  43  31  26  15  21  10
  25  46  48  27  19  39  30  11   7  29  17  28  16  36   0  33  32  34
  37   9  49   4  45   1  40   3  14   6  12  47  35   2   8  42  41  38
  22  13]
[[2.]
 [2.]
 [2.]
 [1.]
 [1.]
 [2.]
 [1.]
 [2.]
 [1.]
 [1.]
 [2.]
 [1.]
 [1.]]


In [77]:
prediction = max(Nearest_Neighbours)


print(f"The predicted flower type is {prediction}, The actual flower type was {x_test[5][4]}")


The predicted flower type is [2.], The actual flower type was 2
